### ISSUE TITLE
Metadata created in Editor should provide correct CSW-URL in OwnCollection

### ISSUE THREAD

**Issue by grmpfhmbl** [ZGIS/smart-portal-backend#16]
Example: When started locally with a correctly configured local CSW, the URL in "my collection" still points to "smart-project.info". (might be a backend-bug)

see also: https://github.com/ZGIS/smart-portal-backend/issues/20

**Comment by allixender** [comment]
That would be here: https://github.com/ZGIS/smart-portal-backend/blob/master/app/services/OwcCollectionsService.scala#L149-L154

**Comment by allixender** [comment]
Ok, let's just start with adding URL to signature
