### ISSUE TITLE
Check why CSW ingester does not get called by backend in prod.

### ISSUE THREAD

**Issue by grmpfhmbl** [ZGIS/smart-portal-backend#18]
Log http-get result!

**Comment by grmpfhmbl** [comment]
This can be closed, once the ENV variable is set to the URL without trailing "/" in cluster.

**Comment by allixender** [comment]
@grmpfhmbl 

Updated env:

PYCSW_URL = http://pycsw:8080
CSWI_URL = http://cswingester-dev:9000

But, what if the call goes wrong and the response future onFailure?

Test shows that the call arrives at the ingester and a update run starts. But could it be that there is some condition that the first time it is called it doesn't merge the whole new pycsw stuff? (would be an ingester issue, we need to keep an eye on it.

**Comment by allixender** [comment]
make IngesterUpdateFuture dependent on InsertResponseFuture, because only if insert future completes (ideally successfully) then ingester is logical to start.
