### ISSUE TITLE
Make OWS Context document implementation compliant to standard and internal class naming consistent

### ISSUE THREAD

**Issue by grmpfhmbl** [ZGIS/smart-portal-backend#25]
The OGC OWS Context GeoJSON Encoding Standard was finalised and published 2017-04-06.

https://portal.opengeospatial.org/files/?artifact_id=68826

The current implementation in Backend and Webgui (from November 2016) rely on preliminary GeoJson results from Atom encoding mappings from OWS-10 TestBed working groups during the last years, before an official OWC GeoJson encoding was standardised.  We are currently not supporting the ATOM encoding.

https://github.com/ZGIS/smart-owc-geojson/issues/1

- [x] UploadedFileProperties - This should not be an offering but a link in "xz.features[i].properties.links.data[j]". See "7.1.2.12 contentByRef" and it's example.
- [x] The GetFile thingy should be done by "xz.features[i].properties.links.data[j]"
- [x] Implications for the database model and the DAO

**Comment by allixender** [comment]
completely overhauled
