### ISSUE TITLE
Data upload

### ISSUE THREAD

**Issue by allixender** [ZGIS/smart-portal-backend#3]
- [x] to local tmp disk at service container and from there into Cloud Storage bucket (direct streaming from Play via chunks into Google Java toolkit problematic right now, don't know how)
- [x] user needs to be able to keep reference in own collection / favourites (e.g. own data OWC collection)

- ~~Metadata record needs to be inserted into CSW~~
- ~~external upload by provided link?~~ in #15

**Comment by grmpfhmbl** [comment]
I'll implement a upload for small files.

**Comment by allixender** [comment]
Was blocked by cluster config. Cluster now Cloud Storage enabled. Please continue now.

**Comment by allixender** [comment]
owcDocumentDAO.updateOwcDocument(newDoc, email)
