### ISSUE TITLE
File upload - creating metadata makes automatically public

### ISSUE THREAD

**Issue by mag1984** [ZGIS/smart-portal-backend#31]
The only current way to add a user-upload file to any collection is through the metadata record. However creating the metadata record makes the file automatically public. It is expected that users will upload files to share with group but not necessarily with the public.

**Comment by allixender** [comment]
As discussed, we will add the the copy from collection to other collection feature, which is also needed in other places:

This issue will closed and moved to: https://github.com/ZGIS/nz-gw-hub/issues/7
